# Generated by Django 5.2.3 on 2025-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_seohome'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_id', models.CharField(max_length=75, verbose_name='Código GA')),
            ],
            options={
                'verbose_name': 'Google Analytics',
                'verbose_name_plural': 'Google Analytics',
            },
        ),
    ]
