# Generated by Django 5.2.3 on 2025-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocos',
            options={'ordering': ['id'], 'verbose_name': '3 - Blocos', 'verbose_name_plural': '3 - Blocos'},
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao_1',
            field=models.TextField(blank=True, help_text='Descrição mais longa', null=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao_2',
            field=models.CharField(blank=True, help_text='Descrição mais curta até 200 caracteres', max_length=200, null=True),
        ),
    ]
